<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="ADAT_Test" tests="15" failures="14" timestamp="11 Jun 2019 16:37:25 GMT" time="8.798" errors="0">
  <testcase name="SetEvironmentLevel" time="0.044" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="ADAT_CreateUser" time="1.68" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;udsTransactionID&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "udsTransactionID"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_CreateUser(ADAT.java:70)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_CreateUser -->
  <testcase name="ADAT_CreateUser" time="1.68" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;udsTransactionID&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "udsTransactionID"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_CreateUser(ADAT.java:70)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_CreateUser -->
  <testcase name="ADAT_CreatePin" time="2.053" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;FDM-PHONE-PIN&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "FDM-PHONE-PIN"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_CreatePin(ADAT.java:86)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_CreatePin -->
  <testcase name="ADAT_CreatePin" time="2.057" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;FDM-POSTCARD-PIN&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "FDM-POSTCARD-PIN"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_CreatePin(ADAT.java:86)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_CreatePin -->
  <testcase name="ADAT_PhoneVelocity" time="1.079" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:113)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_PhoneVelocity" time="1.089" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PhoneVelocity(ADAT.java:113)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PhoneVelocity -->
  <testcase name="ADAT_PostcardVelocity" time="1.102" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:104)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_AddressVelocity" time="1.108" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:95)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_PostcardVelocity" time="1.114" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_PostcardVelocity(ADAT.java:104)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_PostcardVelocity -->
  <testcase name="ADAT_AddressVelocity" time="1.12" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;&amp;lt;rf11:advice&amp;gt;&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "<rf11:advice>"
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT_Endpoints.ADAT_EvaluateRisk(ADAT_Endpoints.java:187)
at ADAT_Application.ADAT_Endpoints.VelocityCheck(ADAT_Endpoints.java:24)
at ADAT_Application.ADAT.ADAT_AddressVelocity(ADAT.java:95)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_AddressVelocity -->
  <testcase name="ADAT_VerifyPin" time="2.035" classname="ADAT_Application.ADAT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.sun.xml.internal.messaging.saaj.soap.impl.ElementImpl.addTextNode(Unknown Source)
at ADAT_Application.ADAT_Endpoints.ADAT_VerifyPin(ADAT_Endpoints.java:148)
at ADAT_Application.ADAT.ADAT_VerifyPin(ADAT.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin -->
  <testcase name="ADAT_VerifyPin" time="2.084" classname="ADAT_Application.ADAT">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.sun.xml.internal.messaging.saaj.soap.impl.ElementImpl.addTextNode(Unknown Source)
at ADAT_Application.ADAT_Endpoints.ADAT_VerifyPin(ADAT_Endpoints.java:148)
at ADAT_Application.ADAT.ADAT_VerifyPin(ADAT.java:128)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin -->
  <testcase name="ADAT_VerifyPin_Invalid" time="3.076" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;The provided authentication credentials are not correct.&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "The provided authentication credentials are not correct."
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:151)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
  <testcase name="ADAT_VerifyPin_Invalid" time="3.094" classname="ADAT_Application.ADAT">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;The provided authentication credentials are not correct.&amp;quot;
     but: was &amp;quot;com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "The provided authentication credentials are not correct."
     but: was "com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at ADAT_Application.ADAT.ADAT_VerifyPin_Invalid(ADAT.java:151)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- ADAT_VerifyPin_Invalid -->
</testsuite> <!-- ADAT_Test -->
