<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="2" name="USRC_Test" tests="15" failures="4" timestamp="28 Jun 2019 18:44:10 GMT" time="65.03" errors="0">
  <testcase name="SetEvironmentLevel" time="0.045" classname="SupportClasses.Environment">
    <skipped/>
  </testcase> <!-- SetEvironmentLevel -->
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="6.631" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="11.129" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="16.555" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="21.705" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="26.791" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="31.622" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="36.099" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="40.315" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;UNKNOWN_ERROR_CODE&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"UNKNOWN_ERROR_CODE","message":"code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment_EmailaAsUserId(USRC_FDM.java:153)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="40.458" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;USERID_SPECIAL_CHAR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;We were unable to process your request. Please try again.&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WERL&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_SPECIAL_CHAR","message":"We were unable to process your request. Please try again.","contextList":["SENDER"],"source":"WERL"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment_EmailaAsUserId(USRC_FDM.java:153)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="45.097" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="42.793" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="43.102" classname="USRC_Application.USRC_FDM"/>
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="42.071" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;UNKNOWN_ERROR_CODE&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"UNKNOWN_ERROR_CODE","message":"code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment_EmailaAsUserId(USRC_FDM.java:153)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" time="41.669" classname="USRC_Application.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;successful\&amp;quot;:true&amp;quot;
     but: was &amp;quot;{&amp;quot;successful&amp;quot;:false,&amp;quot;errorList&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;UNKNOWN_ERROR_CODE&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal&amp;quot;,&amp;quot;contextList&amp;quot;:[&amp;quot;SENDER&amp;quot;],&amp;quot;source&amp;quot;:&amp;quot;WIDM&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"UNKNOWN_ERROR_CODE","message":"code 500, message Failed to execute SendEmailEvent.\n ERROR MESSAGE:\nPxEnvironmentException:Error sending email\n ProcessStep::Unknown TabName: null ERRORLEVEL::Fatal","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC_Application.USRC_FDM.EndtoEndEnrollment_EmailaAsUserId(USRC_FDM.java:153)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment" time="0.0" classname="USRC_Application.USRC_FDM">
    <ignored/>
  </testcase> <!-- EndtoEndEnrollment -->
  <testcase name="EndtoEndEnrollment_UserID" time="0.0" classname="USRC_Application.USRC_FDM">
    <ignored/>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- USRC_Test -->
