<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="WTC-5159473-l2" name="USRC.USRC_FDM" tests="4" failures="1" timestamp="21 Jan 2020 17:03:24 GMT" time="9.167" errors="0">
  <testcase name="CreateNewUsers" time="6.198" classname="USRC.USRC_FDM"/>
  <testcase name="CreateNewUsers" time="2.969" classname="USRC.USRC_FDM">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;successful\&quot;:true&quot;
     but: was &quot;{&quot;successful&quot;:false,&quot;errorList&quot;:[{&quot;code&quot;:&quot;USERID_TAKEN&quot;,&quot;message&quot;:&quot;This user ID has already been chosen by someone else. Please choose another user ID.&quot;,&quot;contextList&quot;:[&quot;SENDER&quot;],&quot;source&quot;:&quot;WIDM&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"USERID_TAKEN","message":"This user ID has already been chosen by someone else. Please choose another user ID.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_FDM.CreateNewUsers(USRC_FDM.java:186)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CreateNewUsers -->
  <testcase name="EndtoEndEnrollment_EmailaAsUserId" classname="USRC.USRC_FDM">
    <skipped/>
  </testcase> <!-- EndtoEndEnrollment_EmailaAsUserId -->
  <testcase name="EndtoEndEnrollment_UserID" classname="USRC.USRC_FDM">
    <skipped/>
  </testcase> <!-- EndtoEndEnrollment_UserID -->
</testsuite> <!-- USRC.USRC_FDM -->
